version: '3'
services:
  db:
    image: mysql:5.7.24
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/stories_app
    ports:
      - "3000:3000"
    links:
      - db:mysql
    depends_on:
      - db  